modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.sporeexposure]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sporeexposure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sporeexposure]]
    modId="spore"
    mandatory=true
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
    modId="sporeexposure"
    version="1.0.0"
    displayName="Spore Exposure"
    description='''
        An addon for the Spore mod.
        Adds a progressive infection system when attacked by Spore entities.
        Protect yourself with the Chemical Protective Helmet!
    '''
